ALTER TABLE invoices
  ADD COLUMN IF NOT EXISTS invoice_type VARCHAR(30) DEFAULT 'TAX_INVOICE',
  ADD COLUMN IF NOT EXISTS parent_invoice_id VARCHAR(50) REFERENCES invoices(id),
  ADD COLUMN IF NOT EXISTS version INT DEFAULT 1 NOT NULL;
