CREATE TABLE IF NOT EXISTS contract_templates (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  structure_type VARCHAR(50) DEFAULT 'SuccessFee',
  default_success_fee_pct FLOAT,
  default_min_fee FLOAT,
  default_max_fee FLOAT,
  default_retainer_amount FLOAT,
  default_replacement_period_days INT DEFAULT 90,
  default_guarantee_period_days INT DEFAULT 90,
  default_payment_terms VARCHAR(100) DEFAULT '30 Days',
  default_currency VARCHAR(10) DEFAULT 'INR',
  default_late_payment_clause TEXT,
  default_travel_expenses_clause TEXT,
  default_exclusivity BOOLEAN DEFAULT TRUE,
  default_non_poaching_months INT DEFAULT 12,
  default_confidentiality BOOLEAN DEFAULT TRUE,
  is_active BOOLEAN DEFAULT TRUE,
  created_by VARCHAR(255),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
